name: Deploy to docker hub

on:
  push:
    branches:    
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      IMAGE_TAG: latest
      DOCKER_USERNAME: darkmattercoder
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image
        if: success()
        run: ./build-dockerimage.sh ${DOCKER_USERNAME}/${GITHUB_REPOSITORY}:${IMAGE_TAG} .
      - name: Push to docker registry
        if: success()
        run: docker push ${DOCKER_USERNAME}/${GITHUB_REPOSITORY}:${IMAGE_TAG}