name: Deploy to docker hub

on: [push, pull_request, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      IMAGE_TAG: latest
      DOCKER_USERNAME: darkmattercoder
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image
        if: success()
        run: ci/build-dockerimage.sh ${DOCKER_USERNAME}/${GITHUB_REPOSITORY} ${IMAGE_TAG} .
      # - name: Push to docker registry
      #   if: success()
      #   run: ./dockerhub-push ${DOCKER_USERNAME}/${GITHUB_REPOSITORY} ${IMAGE_TAG}